### PR TITLE
Support setting package control version and repo

### PR DESCRIPTION
**Pull request by salimane**
- Support setting package control version and repo
- Update sublime text download urls
- Add missing rspec tests

cc @seanknox

### CODE REVIEW

**Comment by seanknox** [comment]
:+1: Thanks for this.

**Comment by salimane** [comment]
a new tag release would be awesome @seanknox :)

**Comment by seanknox** [comment]
done! made you a maintainer so you can do it yourself in the future. :)

**Comment by salimane** [comment]
@seanknox thanks :+1:

**Pull request merged**
